### ISSUE TITLE
on/off toggle for hits

### ISSUE THREAD

**Issue by oui3kings** [e107inc/hits#6]
Assuming someone has the shortcode in their news template, would it be possible to add an on/off toggle for the views to be seen or not maybe under the Advanced Options tab of submit news?

**Comment by oui3kings** [comment]
Or rather than the on/off idea, is there a way for it to be a shortcode to make it hits visible to a user class or user classes

**Comment by CaMer0n** [comment]
@oui3kings You can use the menu-manager options to select the visibility of the menu item. 

![image](https://user-images.githubusercontent.com/2825679/105566325-690fb980-5ce0-11eb-82e6-e80b39f71d89.png)
